import type {Metadata} from "next";
import {Bricolage_Grotesque, Fira_Sans} from "next/font/google";
import "./globals.css";


const bricolage = Bricolage_Grotesque({
    variable: "--font-bricolage-grotesque",
    subsets: ["latin"]
})

const firaSans = Fira_Sans({
    variable: "--font-fira-sans",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"]
})

export const metadata: Metadata = {
    title: "GSAP animations",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en"
              className={`${firaSans.variable} ${bricolage.variable}`}
        >
        <body>
        <main>{children}</main>
        </body>
        </html>
    );
}
